### ISSUE TITLE
Navigating to blog posts results in TypeError: Unexpected MODIFIER at 9, expected END error

### ISSUE THREAD

**Issue by hbuchel** [enhance-dev/enhance-blog-template#8]
Hello, I encounter the following error after running `npm start` and clicking on any blog post:

```
TypeError: Unexpected MODIFIER at 9, expected END
    at mustConsume (E:\projects\enhance-test\node_modules\path-to-regexp\dist\index.js:114:15)
    at parse (E:\projects\enhance-test\node_modules\path-to-regexp\dist\index.js:172:9)
    at stringToRegexp (E:\projects\enhance-test\node_modules\path-to-regexp\dist\index.js:329:27)
    at pathToRegexp (E:\projects\enhance-test\node_modules\path-to-regexp\dist\index.js:407:12)
    at backfill (file:///E:/projects/enhance-test/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/_backfill-params.mjs:17:17)
    at Object.api (file:///E:/projects/enhance-test/node_modules/@enhance/arc-plugin-enhance/src/http/any-catchall/router.mjs:86:20)
    at async combined (E:\projects\enhance-test\node_modules\@enhance\arc-plugin-enhance\node_modules\@architect\functions\src\http\async\index.js:36:20)
```

The server starts up and I can view the home page at http://localhost:3333, but navigating to any of the sample blog posts results in that error. Am I missing any setup steps apart from the `npm install` then `npm start`?

This is after a fresh `npm install` and without changes to the codebase. I'm on:
- Windows
- npm version 9.7.2
- node version 20.3.1

**Comment by macdonst** [comment]
@hbuchel, thanks for the bug report. It's Canada Day so I'm not near my Windows laptop. It might take me a couple of days before I'm able to reproduce the issue. I know it doesn't help but I can't reproduce the issue on MacOS node 18 or 20.

**Comment by macdonst** [comment]
@hbuchel back at my desk today with access to a Windows computer and I can confirm the bug is reproducible on Windows. Looking into it now.

**Comment by macdonst** [comment]
@hbuchel thanks for your patience on this one. I've updated the dependencies in the blog template to fix the Windows-related issue. Give it a whirl and let me know if it resolves your issue. It should, we've tested it on multiple Windows boxes.

**Comment by hbuchel** [comment]
@macdonst yes, that worked for me! Cloned latest and the error is no longer present and I can navigate to individual pages. Thanks!

**Comment by macdonst** [comment]
@hbuchel thanks for reporting the bug. If you run into any other issues don't hesitate to reach out in the issue tracker or on our Discord.
